---
name: xfo-stable

description: Fedora Image made by Gasterboi2012.


base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / 
        
  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka
      
  - type: dnf
    repos:
      nonfree: negativo17
      copr:
        - imput/helium
        - g3tchoo/prismlauncher
    install:
      packages:
        - helium
        - steam
        - prismlauncher
        - kitty 
        - https://vencord.dev/download/vesktop/amd64/rpm
        - nvim
        - fastfetch
        - gnome-disk-utility
        - helium-bin
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - konsole
        - vim
        - nano
        
  - type: default-flatpaks
    configurations:
      - notify: false 
        scope: system
        install: 
          - org.vinegarhq.Sober
          - ai.lmstudio.lm-studio
      - scope: user 

  - type: signing 
